
FROM p/alpine/tiny_ssh
RUN apk add build-base autoconf automake openssl-dev openssl curl-dev; \
		supervisor git; \
	rm -rf /var/cache;

RUN useradd pissnet;

ENV WORKDIR=/home/pissnet/pissircd
ENV HOME=/home/pissnet
ENV TZ=America/Sao_Paulo

#VOLUME /home/pissnet/unrealircd

WORKDIR $HOME

ARG BRANCH

RUN chown -R pissnet:users .; \
	rm -rf unrealircd/*;

USER pissnet

RUN git clone --single-branch --depth 1 https://github.com/pissnet/pissircd -b $BRANCH

WORKDIR $WORKDIR

# RUN ./Config

# if for some reason don't want to call Config (both seem to work)
RUN \
./autogen.sh && \
	./configure --with-showlistmodes --enable-ssl --enable-libcurl \
		--with-nick-history=2000 --with-permissions=0600 --enable-dynamic-linking \
		--disable-asan


# one of the certificates fail to create if it doesn't receive any input
# hence this line is necessary even if you run Config

RUN echo -e 'make pem\n\n\n\n\n\n' | bash -

RUN mkdir -p $HOME/unrealircd/tmp $HOME/unrealircd/conf/tls; \
	cp server.cert.pem server.key.pem server.req.pem $HOME/unrealircd/conf/tls

RUN make -j4; \
	make install;

RUN make clean;

WORKDIR $HOME/unrealircd

ADD --chown=pissnet:users conf conf
ADD --chown=pissnet:users data data

USER pissnet

EXPOSE 22 6667 6697 6900

ENV ASAN_OPTIONS="abort_on_error=1:disable_coredump=0:unmap_shadow_on_exit=1:log_path=/home/pissnet/unrealircd/tmp/unrealircd_asan:detect_leaks=0"

ADD 30-unrealircd.conf /etc/supervisord.d/

#REM tbc
