
FROM alpine:latest
RUN apk add shadow build-base autoconf automake bash openssl-dev openssl curl-dev; \
	rm -rf /var/cache;

RUN useradd pissnet;

ENV WORKDIR=/home/pissnet/pissircd
ENV HOME=/home/pissnet
ENV TZ=America/Sao_Paulo

#VOLUME /home/pissnet/unrealircd

WORKDIR $HOME

ADD pissircd pissircd

ARG BRANCH

RUN chown -R pissnet:users .; \
	rm -rf unrealircd/*;

WORKDIR $WORKDIR

USER pissnet

# RUN ./Config

# if for some reason don't want to call Config (both seem to work)
RUN \
./autogen.sh && \
	./configure --with-showlistmodes --enable-ssl --enable-libcurl \
		--with-nick-history=2000 --with-permissions=0600 --enable-dynamic-linking \
		--disable-asan


# one of the certificates fail to create if it doesn't receive any input
# hence this line is necessary even if you run Config

RUN echo -e 'make pem\n\n\n\n\n\n' | bash -

RUN mkdir -p $HOME/unrealircd/tmp $HOME/unrealircd/conf/tls; \
	cp server.cert.pem server.key.pem server.req.pem $HOME/unrealircd/conf/tls

RUN make -j4; \
	make install;

RUN make clean;

USER root

WORKDIR $HOME/unrealircd

EXPOSE 6667 6697 6900

USER pissnet

#REM tbc
