
FROM alpine:latest

# tiny ssh
RUN apk add shadow bash curl vim less file findutils iputils iproute2 wget \
	openssh-server supervisor;

RUN useradd -U pissnet;

# ENV WORKDIR=/home/pissnet/pissircd
# ENV HOME=/home/pissnet
ENV TZ=America/Sao_Paulo

WORKDIR $HOME

EXPOSE 22

RUN ssh-keygen -A

ADD 50-sshd.conf /etc/supervisord.d/

CMD /usr/bin/supervisord -n
