
FROM alpine:latest

# tiny ssh
RUN apk add shadow bash curl vim less file findutils iputils iproute2 wget \
	openssh-server;

RUN useradd -U pissnet;

# ENV WORKDIR=/home/pissnet/pissircd
# ENV HOME=/home/pissnet
ENV TZ=America/Sao_Paulo

WORKDIR $HOME

EXPOSE 22

RUN ssh-keygen -A

ADD init.sh /usr/local/sbin/init.sh

CMD /usr/local/sbin/init.sh

